# Generated by Django 4.1.1 on 2022-12-18 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquota',
            name='quota_date',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
    ]
