# Generated by Django 4.1.1 on 2022-12-18 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_dailyquota_quota_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexpediture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexpediture',
            name='expenditure_date',
            field=models.DateField(default=datetime.date(2022, 12, 18)),
        ),
        migrations.AddField(
            model_name='studentexpediture',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
