# Generated by Django 4.1.1 on 2022-12-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentexpediture_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexpediture',
            name='daily_quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_expeditures', to='students.dailyquota'),
        ),
    ]
