# Generated by Django 4.1.1 on 2023-05-24 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_mealcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("claimant_name", models.CharField(max_length=255, null=True)),
                ("claimant_email", models.EmailField(max_length=254, null=True)),
                (
                    "claimant_contact_number",
                    models.CharField(max_length=255, null=True),
                ),
                ("claimant_address", models.CharField(max_length=255, null=True)),
                ("policy_number", models.CharField(max_length=255, null=True)),
                ("policy_id", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("reference_number", models.CharField(max_length=255, null=True)),
                ("reason", models.CharField(max_length=255, null=True)),
                ("incident_date", models.DateField(null=True)),
                ("incident_details", models.CharField(max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("creator", models.CharField(max_length=255, null=True)),
                ("validator", models.CharField(max_length=255, null=True)),
                ("repair_agent", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="dailyquota",
            name="quota_date",
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
        migrations.AlterField(
            model_name="studentexpediture",
            name="expenditure_date",
            field=models.DateField(default=datetime.date(2023, 5, 24)),
        ),
    ]
