# Generated by Django 4.1.1 on 2023-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_claim_alter_dailyquota_quota_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="created",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="claim",
            name="modified",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
