# Generated by Django 4.1.1 on 2023-05-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_alter_claim_created_alter_claim_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="claim",
            name="modified",
            field=models.DateTimeField(),
        ),
    ]
